### ISSUE TITLE
request to update example link

### ISSUE THREAD

**Issue by Anupama-Github** [kitsilanosoftware/CppSharpTizen#1]
The link shared in readme file opens to a 404 not found error page could you please update the link?

Thank you

**Comment by bobsummerwill** [comment]
Head to upstream repo.
This is a four year old fork!

**Comment by bobsummerwill** [comment]
Not fork - I mean four year old bindings.
So four year old version of CppSharp against four year old Tizen APIs which aren't even shipped anymore :-)
